### ISSUE TITLE
core: wait for text in device logs

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-tooling-qa#17]
Implement getting logs from devices/emulators/simulators.
If possible implement also mechanism to clear logs (or get logs in a time frame).

Use case:
We can use device logs to assert something happened (for example app restart).
We can get logs and assert app restart on js changes, but later if we modify css we need to have a way to assert no restart is performed (based on logs) and this assert should not take in to account previous restart when js was synced.

**Comment by rosen-vladimirov** [comment]
Implemented in device tests.
