### ISSUE TITLE
test: add verification for modules version in platforms folder

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-tooling-qa#6]
We had some kind of assert for this in the old solution, but implementation is awful:
https://github.com/NativeScript/nativescript-cli-tests/commit/c41b37e624f1778544e9c49e8ec0720a827e09b2

Try to do better implementation:
- Do not get modules version from package.json, get it from node_modules (otherwise `~` and `^` should be respected and we should check which is the correct package version with some request to npm).
- Check values in json, not just check if string is somewhere there.

**Comment by rosen-vladimirov** [comment]
Not applicable with webpack workflow.
